# Generated by Django 5.1.2 on 2024-10-15 23:29

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_stage', api.models.EmptyStringToNoneField(choices=[('application_review', api.models.InterviewStage['APPLICATION_REVIEW']), ('preliminary_phone_screen', api.models.InterviewStage['PRELIMINARY_PHONE_SCREEN']), ('phone_interview', api.models.InterviewStage['PHONE_INTERVIEW']), ('take_home_test', api.models.InterviewStage['TAKE_HOME_TEST']), ('interviews_passed', api.models.InterviewStage['INTERVIEWS_PASSED'])], default='application_review')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='unique_interview_per_job_for_candidate')],
            },
        ),
    ]
